# Generated by Django 3.1 on 2020-09-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200902_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='dob',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
