# Generated by Django 3.1 on 2020-09-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20200904_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emaill',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='namee',
            new_name='name',
        ),
    ]
