# Generated by Django 3.1 on 2020-09-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20200904_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='emaile',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
